namespace FSBS.Domain.Entities;

/// <summary>
/// Root base type for all domain entities. Provides a surrogate primary key
/// that maps to a PostgreSQL <c>uuid</c> column with a <c>uuid_generate_v4()</c> default.
/// </summary>
public abstract class EntityBase
{
    /// <summary>
    /// Surrogate primary key. Generated by the database on insert; never reassigned.
    /// The concrete column name (e.g. <c>booking_id</c>) is set per entity in its
    /// Fluent API configuration.
    /// </summary>
    public Guid Id { get; set; }
}
